### ISSUE TITLE
大佬，求更新。现在无法正确下载连载的最新一话了

### ISSUE THREAD

**Issue by breezeit** [EternalPhane/UserScripts#11]
大佬，求更新。
现在无法正确下载所有连载的最新一话了，只有一个22b的文件。
如果不是连载，只有单本的，也是无法正确下载，只有22b空文件。

**Comment by breezeit** [comment]
测试了好像是7月某日之后的都不能用脚本下载了。之前的可以用现在的脚本下载

**Comment by C38969** [comment]
现在还可以使用下载吗？我在图片右侧没有找到下载按钮
